### ISSUE TITLE
Deprecate/Hand over Astar's `ink-playground` project

### ISSUE THREAD

**Issue by cmichi** [paritytech/ink-playground#170]
The first Google result for ink! playground is https://ink-playground.com, which seems to be inactive. This is irritating for users and it happens from time to time that people ask questions about it in the public channel, because they think this project is meant in the public talks.

It was developed under a W3F grant for Astar Network and the repo is at https://github.com/AstarNetwork/ink-playground.

Ideally we would ask them to archive that repo and make a PR which adds a note to their readme that the project is discontinued and refer to the Parity one instead.

In terms of the domain we could also talk to them about either a redirect or a handover. This is something @darko-mijic could help with.

**Comment by achimcc** [comment]
I contacted a dev on Astar on Discord about it.

**Comment by darko-mijic** [comment]
I have reached out to a couple of people. I will keep the issue up-to-date.

**Comment by darko-mijic** [comment]
I have arranged the domain transfer and DevOps people to handle it on the Parity side. It will be completed next week.

**Comment by achimcc** [comment]
Done.
